language: ruby

rvm: 
  - 1.9.3
  - 2.0.0

env: DB=postgresql

before_script:
  - psql -c 'create database chromotype_test' -U postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test:all
